version: '3.8'
services:
  db:
    container_name: db_c
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:${DATABASE_PORT}
  nextjs:
    depends_on:
      - db
    container_name: next_c
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${NEXT_PORT}:${NEXT_PORT}
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:${DATABASE_PORT}/postgres
      - AWS_PUBLIC_KEY=${AWS_PUBLIC_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./public
          target: /app/public
          action: sync
